services:
  serv:
    build: ./requirements/nginx
    ports:
      - "3000:80"
    stdin_open: true
    tty: true
    env_file:
      - ../secrets/db_password.txt
      - ../secrets/db_root_password.txt
    networks:
      - inception_net

  db:
    build: ./requirements/mariadb
    stdin_open: true
    tty: true
    networks:
      - inception_net
  
  # wp:
  #   build: ./wordpress

# volumes:

networks:
  inception_net:
    driver: bridge