services:

  mariadb:
    container_name: mariadb
    image: mariadb:v1.0
    build: 
      context: ./requirements/mariadb
    stdin_open: true
    tty: true
    env_file:
      - ../secrets/credentials.txt
      - ../secrets/db_password.txt
      - ../secrets/db_root_password.txt
    expose:
      - "3306"
    networks:
      - inception_net
    stop_grace_period: 1s
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping --host=localhost -p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 1s
      retries: 5
      start_period: 5s
  
  wordpress:
    build: 
      context: ./requirements/wordpress
    image: wordpress:v1.0
    stdin_open: true
    tty: true
    env_file:
      - ../secrets/credentials.txt
      - ../secrets/db_password.txt
      - ../secrets/db_root_password.txt
      - .env
    stop_grace_period: 1s
    networks:
      - inception_net
    depends_on:
      mariadb:
        condition: service_healthy

  nginx:
    build: 
      context: ./requirements/nginx
    image: nginx:v1.0
    ports:
      - "3000:80"
    stdin_open: true
    tty: true
    env_file:
      - ../secrets/db_password.txt
      - ../secrets/db_root_password.txt
    networks:
      - inception_net


volumes:
  db_data:
    driver: local

networks:
  inception_net:
    name: inception_net
    driver: bridge